version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - VT_API_KEY=${VT_API_KEY}
      - NVD_API_KEY=${NVD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  ollama_data:
